### PR TITLE
fixed vifino/sled#10; this voodoo ain't nice, but it works

### PR DESCRIPTION
**Pull request by marenz2569**
Mabye you should think about using a real math library :D

### CODE REVIEW

**Comment by marenz2569** [comment]
hint: I'd like to have matix_move operations. With these solving all the problems would be much easier.

**Comment by marenz2569** [comment]
I just came up with a lot of cleanup in my mind. I will implement it later today.

**Comment by vifino** [comment]
Heh, real math libraries are for noobs! 😉 

Looking forward to the cleanup!

**Comment by marenz2569** [comment]
Ok, this works now and the code is much cleaner, but still unreadable.

**Comment by vifino** [comment]
Do you want me to merge it now?

**Comment by marenz2569** [comment]
Yes it is fine now.

**Pull request merged**
