### PR TITLE
fixed bug vifino/sled#31; rewrite modules_init; central outmod pointer

### PR DESCRIPTION
**Pull request by marenz2569**
Why the hell would you even bother having multiple pointers to outmod?

fixed vifino/sled#31

### CODE REVIEW

**Comment by vifino** [comment]
Hey!

Nice changes overall, a bit cleaner, although I would really like it if we could get rid of the `malloc`, allocating a single `int` is not so nice, even though `os_unix` does it too..

It should be rather trivial.

**Comment by marenz2569** [comment]
I renamed outmod to outmod_c as outmod now references to a global pointer to the output module.
We have to pass a pointer to outmodno to the modules_init function to change its value outside the function. Doing this with &outmodno might also work, whilst `int outmodno` is used.

**Comment by marenz2569** [comment]
Yes, doing it this way works.

**Comment by vifino** [comment]
Awesome, thanks.

**Pull request merged**
